# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
#    - name: Build with Maven
#      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#    - name: Update dependency graph
#      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
    
    - name: Synopsys Action Black Duck
      uses: synopsys-sig/synopsys-action@main
#      env:
#        DETECT_PROJECT_NAME: RDJ_java_sec_code_GH_Action
#        DETECT_BLACKDUCK_RAPID_COMPARE_MODE: BOM_COMPARE_STRICT
      with:
        blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN }}
        blackduck_url: ${{ secrets.BLACKDUCK_URL }}
        
        # blackduck_scan_full: true
        # bridge_download_url: https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-action/0.1.72/ci-package-0.1.72-linux64.zip
        github_token: ${{ secrets.GITHUB_TOKEN }}
        blackduck_automation_fixpr: true
        blackduck_scan_failure_severities: "ALL"
        blackduck_automation_prComment: true

